name: uml_for_serverpod
description: "Generate UML diagrams with your .spy.yaml serverpod models."
version: 0.0.2+1
homepage: https://github.com/dabblingwithcode/uml_for_serverpod

environment:
  sdk: ^3.5.0


dependencies:

  args: ^2.7.0
  yaml: ^3.1.3

dev_dependencies:

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

